### ISSUE TITLE
Report number of samples for a Center, Program, etc.

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/dcc-feature-requests#1]
We need a way to know how many samples are associated with a Center | Program | Project | Workflow, etc. so we can know how much processing remains to be done. For instance I want to select Center: THR12, Program:Treehouse, and somehow find out how many samples are there. I can find out how many fastq.gz files exist but there could be 1,2 or 4 fastq.gz files per sample. Also I can see that there are a certain number of .bg files for a Center and Program and that tells me how many samples have been processed, but I cannot find out how many samples are left to do.

**Comment by klearned** [comment]
This is already recorded somewhere, the number of bundles...if there could be a facet for Samples (which reported the number of bundle ids), that'd be great....maybe that would be a weird facet since it would have to be so many items listed. What if there was a radio button at the top of the facets that could toggle between providing numbers by sample (aka bundle) or by file? So all the numbers listed after the facets would show up as number of files or number of samples based on what the user chooses.

**Comment by wshands** [comment]
Closing since issue added to dcc dashboard repo: https://github.com/BD2KGenomics/dcc-dashboard/issues/33
